<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.296">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nelson Brayan Mamani Flores">
<meta name="dcterms.date" content="2023-03-31">

<title>VEC model to analyze the relationship between GDP and energy consumption in Peru, 1971 - 2014</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="VECM_files/libs/clipboard/clipboard.min.js"></script>
<script src="VECM_files/libs/quarto-html/quarto.js"></script>
<script src="VECM_files/libs/quarto-html/popper.min.js"></script>
<script src="VECM_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="VECM_files/libs/quarto-html/anchor.min.js"></script>
<link href="VECM_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="VECM_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="VECM_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="VECM_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="VECM_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">1. Introduction</a></li>
  <li><a href="#the-relationship-between-energy-consumption-and-gdp" id="toc-the-relationship-between-energy-consumption-and-gdp" class="nav-link" data-scroll-target="#the-relationship-between-energy-consumption-and-gdp">2. The relationship between energy consumption and GDP</a></li>
  <li><a href="#econometric-methodology-and-model" id="toc-econometric-methodology-and-model" class="nav-link" data-scroll-target="#econometric-methodology-and-model">3. Econometric methodology and model</a>
  <ul class="collapse">
  <li><a href="#data-and-application" id="toc-data-and-application" class="nav-link" data-scroll-target="#data-and-application">3.1. Data and Application</a></li>
  <li><a href="#unit-root-tests" id="toc-unit-root-tests" class="nav-link" data-scroll-target="#unit-root-tests">3.2. Unit Root Tests</a></li>
  <li><a href="#cointegration-test" id="toc-cointegration-test" class="nav-link" data-scroll-target="#cointegration-test">3.3. Cointegration Test</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">4. Conclusiones</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">VEC model to analyze the relationship between GDP and energy consumption in Peru, 1971 - 2014</h1>
<p class="subtitle lead">Application in Python</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nelson Brayan Mamani Flores </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 31, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="abstract" class="level3">
<h3 class="anchored" data-anchor-id="abstract">Abstract</h3>
<p>This paper presents empirical evidence on the relationship between energy consumption and GDP in Perú during the period 1971 to 2014. The results show that the series are not stationary, i.e., are individually I(1); in addition, we find a long-term relationship between both variables. Through a VECM we estimate short- and long-term elasticities to analyze the dynamics of adjustment. The results show that in the short-term the conservation hypothesis holds (i.e., no evidence of a short-term relationship of energy consumption to GDP). In the long-term, however, we find evidence of a feedback mechanism between both variables. Yet, this paper provides evidence that policymakers can implement policies aimed at energy conservation without hurting economic growth.</p>
<p><strong>Key words:</strong> Energy Consumption, Cointegration Relation, Vector Error Correction Model (VECM), Structural Break, Perú.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p>The oil crisis of the 1970s motivated researchers to study numerous relationships between macroeconomic variables. As a result, researchers began to study the relationships between macroeconomic variables such as oil prices, inflation, economic growth, energy consumption, the exchange rate, and other factors that affect the economy in general. This led to a greater understanding of how these variables are interconnected and how they can affect the economy of a country and the world as a whole. The oil crisis led to a significant increase in energy prices, which in turn had a major impact on the global economy. Also, since energy is a key input for production and consumption, it has become a central research topic in economics.</p>
<p>Given the importance between GDP dynamics and electricity consumption, this article will address the relationship between these variables through an error correction model. For this reason, the specific objective of this work is to provide empirical evidence of the existence or not of a strong relationship (in the short and long term) between energy consumption and GDP in Peru, as well as to analyze that, For the above reason, it is possible to implement environmental policies that promote the efficient use and conservation of energy.</p>
<p>In this sense, this work is an empirical and applied contribution to the scarce literature on energy and its impact on production in Peru.</p>
</section>
<section id="the-relationship-between-energy-consumption-and-gdp" class="level2">
<h2 class="anchored" data-anchor-id="the-relationship-between-energy-consumption-and-gdp">2. The relationship between energy consumption and GDP</h2>
<p>The relationship between energy consumption and GDP is complex and multifaceted. Generally, there is a positive correlation between energy consumption and GDP, as countries with higher levels of economic development tend to consume more energy in order to power their industries, transportation systems, and households. Evidence also shows that it is possible to find a two-way causality between energy consumption and real GDP. In the study carried out by Al-Iriani (2006) for the six countries that make up the Gulf Cooperation Council (Kuwait, Oman, Saudi Arabia, Bahrain, the United Arab Emirates and Qatar), the results obtained indicate that there is unidirectional causality of GDP. . to energy consumption; Soytas, Sari and Ozdemir (2001) found evidence of a one-way causal relationship between energy consumption and GDP in Turkey from the cointegration method and error correction vector analysis.</p>
<p>A priori we could say that the relationship between energy consumption and GDP is complex and depends on a wide range of factors including the level of economic development of a country, its energy policies and the efficiency of its energy systems.</p>
</section>
<section id="econometric-methodology-and-model" class="level2">
<h2 class="anchored" data-anchor-id="econometric-methodology-and-model">3. Econometric methodology and model</h2>
<p>It is known that to avoid obtaining misleading relationships in econometric estimates it is necessary to apply unit root tests to the series in order to determine the stationarity or not of the series. Then, if the series are non-stationary, that is, they have a unit root, it must be proved that they are cointegrated and, thus, have a long-term relationship between them.</p>
<p>Firstly, in this work the ADF (Augmented Dickey-Fuller) test and the KPSS (Kwiatkowski, Phillips, Smichdt and Shin) test were applied to test the order of integration of the series. Additionally, the Zivot-Andrews test was used to determine if the series are stationary or non-stationary in the presence of a possible unit root with structural break.</p>
<p>As mentioned, if the series have a unit root (they are integrated of order one), according to Granger and Newbold (1974), the step to follow is to test cointegration between the series. In addition, the test proposed by Johansen based on the Lagrange Multiplier estimator (MLE) and the cointegration methodology proposed by Johansen and Juselius (1992) were used to prove the existence of a long-term relationship between the variables. The next step is to estimate the VAR Model (p) to determine the number of lags thereof based on the information criteria and thus determine the optimal lags of the VEC Model (p-1).</p>
<section id="data-and-application" class="level3">
<h3 class="anchored" data-anchor-id="data-and-application">3.1. Data and Application</h3>
<p>This is a time series study, which consists of annual time series of GDP and energy consumption, both in per capita terms. The series are obtained from the World Bank, the definition of energy consumption is: Electricity consumption measures the production of electricity generating plants and combined heat and electricity generation plants, minus transmission, distribution and transformation losses, and the own consumption of the plants. On the other hand, GDP per capita is measured at current prices.</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Access the world bank database</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pandas_datareader <span class="im">import</span> wb</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>KWH_PC<span class="op">=</span> <span class="st">'EG.USE.ELEC.KH.PC'</span>     <span class="co"># Series Electrical energy consumption per capita (kWh)</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>PBI_PC<span class="op">=</span> <span class="st">'NY.GDP.PCAP.KN'</span>        <span class="co"># GDP per capita series in USD (Constant prices)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Download the database with the selected variables</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>df1 <span class="op">=</span> wb.download(indicator<span class="op">=</span>[KWH_PC, PBI_PC], country<span class="op">=</span><span class="st">'PER'</span>, start<span class="op">=</span><span class="dv">1971</span>, end<span class="op">=</span><span class="dv">2014</span>).sort_index()</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>df1.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">EG.USE.ELEC.KH.PC</th>
<th data-quarto-table-cell-role="th">NY.GDP.PCAP.KN</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">country</th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td rowspan="5" data-quarto-table-cell-role="th" data-valign="top">Peru</td>
<td data-quarto-table-cell-role="th">1971</td>
<td>388.514407</td>
<td>8784.738435</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1972</td>
<td>406.578668</td>
<td>8848.246104</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1973</td>
<td>410.295619</td>
<td>9158.635033</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1974</td>
<td>426.906110</td>
<td>9763.916538</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1975</td>
<td>435.773811</td>
<td>9930.384340</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename variables and remove country indexed column</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> df1.reset_index(level<span class="op">=</span>[<span class="st">'country'</span>])</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> data.drop(<span class="st">'country'</span>, axis<span class="op">=</span><span class="dv">1</span>).rename(columns<span class="op">=</span>{<span class="st">'EG.USE.ELEC.KH.PC'</span>: <span class="st">'CE'</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>                                                    <span class="st">'NY.GDP.PCAP.KN'</span>: <span class="st">'PBI'</span>})</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CE</th>
<th data-quarto-table-cell-role="th">PBI</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1971</td>
<td>388.514407</td>
<td>8784.738435</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1972</td>
<td>406.578668</td>
<td>8848.246104</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1973</td>
<td>410.295619</td>
<td>9158.635033</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1974</td>
<td>426.906110</td>
<td>9763.916538</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1975</td>
<td>435.773811</td>
<td>9930.384340</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the logarithm of the variables</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'LPBI'</span>] <span class="op">=</span> np.log(data[<span class="st">'PBI'</span>])</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'LCE'</span>] <span class="op">=</span> np.log(data[<span class="st">'CE'</span>])</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="43">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CE</th>
<th data-quarto-table-cell-role="th">PBI</th>
<th data-quarto-table-cell-role="th">LPBI</th>
<th data-quarto-table-cell-role="th">LCE</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1971</td>
<td>388.514407</td>
<td>8784.738435</td>
<td>9.080771</td>
<td>5.962330</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1972</td>
<td>406.578668</td>
<td>8848.246104</td>
<td>9.087975</td>
<td>6.007777</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1973</td>
<td>410.295619</td>
<td>9158.635033</td>
<td>9.122452</td>
<td>6.016878</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1974</td>
<td>426.906110</td>
<td>9763.916538</td>
<td>9.186449</td>
<td>6.056564</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1975</td>
<td>435.773811</td>
<td>9930.384340</td>
<td>9.203354</td>
<td>6.077123</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the graph in time series of the logarithms of the variables</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>plt.style.use(<span class="st">'fivethirtyeight'</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'lines.linewidth'</span>]<span class="op">=</span><span class="fl">1.5</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>data[[<span class="st">'LPBI'</span>,<span class="st">'LCE'</span>]].plot(ax<span class="op">=</span>ax)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Figure1. Energy Consumption Per Capita and Real GDP Per Capita in Peru, 1971-2014'</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Mes'</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Valor'</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="VECM_files/figure-html/cell-7-output-1.png" class="quarto-discovered-preview-image img-fluid"></p>
</div>
</div>
<p>Graph 1 shows the series in logarithms for the study period and Graph 2 shows the first difference of the series in Graph 1. We can see that in graphs 1 and 2, the series are apparently correlated in some periods, but in others , power consumption increases.</p>
<div class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate the first differences of the variables</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'DLPBI'</span>] <span class="op">=</span> (data[<span class="st">'LPBI'</span>]<span class="op">-</span> data[<span class="st">'LPBI'</span>].shift(<span class="dv">1</span>))<span class="op">*</span><span class="dv">100</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'DLCE'</span>] <span class="op">=</span> (data[<span class="st">'LCE'</span>]<span class="op">-</span> data[<span class="st">'LCE'</span>].shift(<span class="dv">1</span>))<span class="op">*</span><span class="dv">100</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>data.head()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CE</th>
<th data-quarto-table-cell-role="th">PBI</th>
<th data-quarto-table-cell-role="th">LPBI</th>
<th data-quarto-table-cell-role="th">LCE</th>
<th data-quarto-table-cell-role="th">DLPBI</th>
<th data-quarto-table-cell-role="th">DLCE</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1971</td>
<td>388.514407</td>
<td>8784.738435</td>
<td>9.080771</td>
<td>5.962330</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1972</td>
<td>406.578668</td>
<td>8848.246104</td>
<td>9.087975</td>
<td>6.007777</td>
<td>0.720331</td>
<td>4.544718</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1973</td>
<td>410.295619</td>
<td>9158.635033</td>
<td>9.122452</td>
<td>6.016878</td>
<td>3.447789</td>
<td>0.910049</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1974</td>
<td>426.906110</td>
<td>9763.916538</td>
<td>9.186449</td>
<td>6.056564</td>
<td>6.399645</td>
<td>3.968618</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1975</td>
<td>435.773811</td>
<td>9930.384340</td>
<td>9.203354</td>
<td>6.077123</td>
<td>1.690558</td>
<td>2.055922</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw the first differences of the series</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>data[[<span class="st">'DLPBI'</span>,<span class="st">'DLCE'</span>]].plot(ax<span class="op">=</span>ax)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Figure2. First difference of energy consumption per capita and real GDP per capita in Perú, 1971-2014'</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'Año'</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Valor'</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="VECM_files/figure-html/cell-9-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>For example, in at least 10 periods, the series appear to go in opposite directions. This result of the preliminary analysis provides a first approximation that gives strength to the hypothesis of this study, which suggests that there is neither a short nor a long-term relationship between energy consumption and GDP, in both directions, that is, from energy consumption to GDP and vice versa. However, in recent years it can be seen that more movements in GDP translate into movements in energy consumption.</p>
<p>In fact, if Graph 3 is observed, which presents a scatter graph with a linear trend, a first approximation can be seen, which indicates that the relationship between energy consumption and GDP is positive for the period of study in Peru.</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the dispersion between variables</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>plt.scatter(data[<span class="st">'LCE'</span>], data[<span class="st">'LPBI'</span>])</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>fit <span class="op">=</span> np.polyfit(data[<span class="st">'LCE'</span>], data[<span class="st">'LPBI'</span>], <span class="dv">1</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>fit_fn <span class="op">=</span> np.poly1d(fit)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>plt.plot(data[<span class="st">'LCE'</span>], fit_fn(data[<span class="st">'LCE'</span>]),<span class="st">'--r'</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">'Figure3. Dispersion between energy consumption per capita and real GDP per capita in Perú, 1971-2014'</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">'LCE'</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'LPBI'</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="VECM_files/figure-html/cell-10-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
<section id="unit-root-tests" class="level3">
<h3 class="anchored" data-anchor-id="unit-root-tests">3.2. Unit Root Tests</h3>
<p>The Augmented Dickey-Fuller (ADF) test and the Kwiatkowski-Phillips-Schmidt-Shin (KPSS) test are both statistical tests commonly used in time series analysis to test for stationarity. Additionally, the Zivot-Andrews test was used to test for a structural break or regime shift in the data. A structural break occurs when there is a significant change in the underlying data generation process of a time series. The null hypothesis of the Zivot-Andrews test is that the time series is stationary and does not have a structural break. The alternative hypothesis is that the time series has a structural break at an unknown point in time. The results are shown below, taking into account deterministic components.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import libraries</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.stattools <span class="im">import</span> adfuller</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dickey &amp; Fuller test with constant for the LCE series</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> data[<span class="st">"LCE"</span>].values</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>result_adf1 <span class="op">=</span> adfuller(X, regression<span class="op">=</span><span class="st">'c'</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'ADF statistic: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_adf1[<span class="dv">0</span>])</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'p-value: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_adf1[<span class="dv">1</span>])</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical values:'</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value <span class="kw">in</span> result_adf1[<span class="dv">4</span>].items():</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'</span><span class="ch">\t</span><span class="sc">%s</span><span class="st">: </span><span class="sc">%.3f</span><span class="st">'</span> <span class="op">%</span> (key, value))</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> result_adf1[<span class="dv">0</span>] <span class="op">&lt;</span> result_adf1[<span class="dv">4</span>][<span class="st">"5%"</span>]:</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Reject the Ho - The time series is stationary"</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Do not reject Ho - The time series is not stationary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF statistic: 1.804410
p-value: 0.998358
Critical values:
    1%: -3.597
    5%: -2.933
    10%: -2.605
Do not reject Ho - The time series is not stationary</code></pre>
</div>
</div>
<section id="results-analysis" class="level5">
<h5 class="anchored" data-anchor-id="results-analysis">Results analysis:</h5>
<p>The results indicate that we cannot reject the null hypothesis (Ho) that the time series is not stationary. This is because the ADF (Augmented Dickey-Fuller) value is greater than the critical values at the 1%, 5%, and 10% significance levels, and the p-value is greater than the 5% significance level. . Therefore, we do not have enough evidence to affirm that the time series is stationary. It is important to highlight that the non-stationarity of the time series can have important implications in its modeling and in making decisions based on it.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dickey &amp; Fuller test with constant and trend for the LCE series</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> data[<span class="st">"LCE"</span>].values</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>result_adf2 <span class="op">=</span> adfuller(X, regression<span class="op">=</span><span class="st">'ct'</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'ADF statistic: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_adf2[<span class="dv">0</span>])</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'p-value: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_adf2[<span class="dv">1</span>])</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical values:'</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value <span class="kw">in</span> result_adf2[<span class="dv">4</span>].items():</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'</span><span class="ch">\t</span><span class="sc">%s</span><span class="st">: </span><span class="sc">%.3f</span><span class="st">'</span> <span class="op">%</span> (key, value))</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> result_adf2[<span class="dv">0</span>] <span class="op">&lt;</span> result_adf2[<span class="dv">4</span>][<span class="st">"5%"</span>]:</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Reject the Ho - The time series is stationary"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Do not reject Ho - The time series is not stationary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF statistic: -0.093686
p-value: 0.993150
Critical values:
    1%: -4.192
    5%: -3.521
    10%: -3.191
Do not reject Ho - The time series is not stationary</code></pre>
</div>
</div>
</section>
<section id="results-analysis-1" class="level5">
<h5 class="anchored" data-anchor-id="results-analysis-1">Results analysis:</h5>
<p>The results indicate that we cannot reject the null hypothesis (Ho) that the LCE time series is not stationary. This is because the ADF (Augmented Dickey-Fuller) value is greater than the critical values at the 1%, 5%, and 10% significance levels, and the p-value is greater than the 5% significance level. . Therefore, we do not have enough evidence to affirm that the LCE time series is stationary. It is important to highlight that the non-stationarity of the time series can have important implications in its modeling and in making decisions based on it. In addition, when using the test with constant and trend, the possible presence of a trend in the time series is taken into account, which may affect its stationarity.</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dickey &amp; Fuller test with constant for the lPBI series</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> data[<span class="st">"LPBI"</span>].values</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>result_adf3 <span class="op">=</span> adfuller(Y, regression<span class="op">=</span><span class="st">'c'</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'ADF statistic: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_adf3[<span class="dv">0</span>])</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'p-value: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_adf3[<span class="dv">1</span>])</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical values:'</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value <span class="kw">in</span> result_adf3[<span class="dv">4</span>].items():</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'</span><span class="ch">\t</span><span class="sc">%s</span><span class="st">: </span><span class="sc">%.3f</span><span class="st">'</span> <span class="op">%</span> (key, value))</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> result_adf3[<span class="dv">0</span>] <span class="op">&lt;</span> result_adf3[<span class="dv">4</span>][<span class="st">"5%"</span>]:</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Reject the Ho - The time series is stationary"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Do not reject Ho - The time series is not stationary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF statistic: -0.502716
p-value: 0.891485
Critical values:
    1%: -3.597
    5%: -2.933
    10%: -2.605
Do not reject Ho - The time series is not stationary</code></pre>
</div>
</div>
</section>
<section id="results-analysis-2" class="level5">
<h5 class="anchored" data-anchor-id="results-analysis-2">Results analysis:</h5>
<p>The results indicate that we cannot reject the null hypothesis (Ho) that the lGDP time series is not stationary. This is because the ADF (Augmented Dickey-Fuller) value is greater than the critical values at the 1%, 5%, and 10% significance levels, and the p-value is greater than the 5% significance level. . Therefore, we do not have sufficient evidence to affirm that the lGDP time series is stationary. It is important to highlight that the non-stationarity of the time series can have important implications in its modeling and in making decisions based on it. Using the constant test assumes that the time series has no deterministic trend, but may have a constant.</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dickey &amp; Fuller test with constant and trend for the lPBI series</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> data[<span class="st">"LPBI"</span>].values</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>result_adf4 <span class="op">=</span> adfuller(Y, regression<span class="op">=</span><span class="st">'ct'</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'ADF statistic: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_adf4[<span class="dv">0</span>])</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'p-value: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_adf4[<span class="dv">1</span>])</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical values:'</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value <span class="kw">in</span> result_adf4[<span class="dv">4</span>].items():</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'</span><span class="ch">\t</span><span class="sc">%s</span><span class="st">: </span><span class="sc">%.3f</span><span class="st">'</span> <span class="op">%</span> (key, value))</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> result_adf4[<span class="dv">0</span>] <span class="op">&lt;</span> result_adf4[<span class="dv">4</span>][<span class="st">"5%"</span>]:</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Reject the Ho - The time series is stationary"</span>)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Do not reject Ho - The time series is not stationary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ADF statistic: -0.994704
p-value: 0.944823
Critical values:
    1%: -4.192
    5%: -3.521
    10%: -3.191
Do not reject Ho - The time series is not stationary</code></pre>
</div>
</div>
</section>
<section id="results-analysis-3" class="level5">
<h5 class="anchored" data-anchor-id="results-analysis-3">Results analysis:</h5>
<p>The results indicate that we cannot reject the null hypothesis (Ho) that the IPBI time series is not stationary. This is because the ADF (Augmented Dickey-Fuller) value is greater than the critical values at the 1%, 5%, and 10% significance levels, and the p-value is greater than the 5% significance level. . Therefore, we do not have enough evidence to affirm that the GDPl time series is stationary. When using the test with constant and trend, the possible presence of a trend and a constant in the time series is taken into account, which may affect its stationarity. It is important to highlight that the non-stationarity of the time series can have important implications in its modeling and in decision-making based on it.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import libraries</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.stattools <span class="im">import</span> kpss</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Kwiatkowski–Phillips–Schmidt–Shin test with constant for the lCE series</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>result_kpss1 <span class="op">=</span> kpss(X, regression<span class="op">=</span><span class="st">'c'</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'KPSS Statistic: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_kpss1[<span class="dv">0</span>])</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'p-value: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_kpss1[<span class="dv">1</span>])</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical values:'</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value <span class="kw">in</span> result_kpss1[<span class="dv">3</span>].items():</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'</span><span class="ch">\t</span><span class="sc">%s</span><span class="st">: </span><span class="sc">%.4f</span><span class="st">'</span> <span class="op">%</span> (key, value))</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> result_kpss1[<span class="dv">0</span>] <span class="op">&lt;</span> result_kpss1[<span class="dv">3</span>][<span class="st">"5%"</span>]:</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Reject the Ho - The time series is not stationary"</span>)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Do not reject Ho - The time series is stationary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>KPSS Statistic: 0.876762
p-value: 0.010000
Critical values:
    10%: 0.3470
    5%: 0.4630
    2.5%: 0.5740
    1%: 0.7390
Do not reject Ho - The time series is stationary</code></pre>
</div>
</div>
</section>
<section id="results-analysis-4" class="level5">
<h5 class="anchored" data-anchor-id="results-analysis-4">Results analysis:</h5>
<p>LCE series indicate that we cannot reject the null hypothesis (Ho) that the time series is not stationary. This is because the value of the KPSS statistic is greater than the critical values at all significance levels, and the p-value is less than the 1% significance level.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Kwiatkowski–Phillips–Schmidt–Shin test with constant and trend for the lCE series</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>result_kpss2 <span class="op">=</span> kpss(X, regression<span class="op">=</span><span class="st">'ct'</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'KPSS Statistic: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_kpss2[<span class="dv">0</span>])</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'p-value: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_kpss2[<span class="dv">1</span>])</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical values:'</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value <span class="kw">in</span> result_kpss2[<span class="dv">3</span>].items():</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'</span><span class="ch">\t</span><span class="sc">%s</span><span class="st">: </span><span class="sc">%.4f</span><span class="st">'</span> <span class="op">%</span> (key, value))</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> result_kpss2[<span class="dv">0</span>] <span class="op">&lt;</span> result_kpss2[<span class="dv">3</span>][<span class="st">"5%"</span>]:</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Reject the Ho - The time series is not stationary"</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Do not reject the Ho - The time series is stationary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>KPSS Statistic: 0.206136
p-value: 0.013699
Critical values:
    10%: 0.1190
    5%: 0.1460
    2.5%: 0.1760
    1%: 0.2160
Do not reject the Ho - The time series is stationary</code></pre>
</div>
</div>
</section>
<section id="results-analysis-5" class="level5">
<h5 class="anchored" data-anchor-id="results-analysis-5">Results analysis:</h5>
<p>The results of the Kwiatkowski-Phillips-Schmidt-Shin (KPSS) test with constant and trend for the ICE series indicate that we cannot reject the null hypothesis (Ho) that the time series is not stationary. This is because the value of the KPSS statistic is less than the critical values at all significance levels, and the p-value is less than the 1% significance level.</p>
<p>When using the test with constant and trend, the possible presence of a trend and a constant in the time series is taken into account, which may affect its stationarity.</p>
<p>Therefore, the results suggest that the lCE series has a deterministic trend, which means that its mean is not constant over time. This can have important implications for time series modeling and decision making, as a trend can affect the prediction and interpretation of the results. It is important to take these results into account when performing analysis and modeling of the lCE time series.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Kwiatkowski–Phillips–Schmidt–Shin test with constant for the lCE series</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>result_kpss3 <span class="op">=</span> kpss(Y, regression<span class="op">=</span><span class="st">'c'</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'KPSS Statistic: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_kpss3[<span class="dv">0</span>])</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'p-value: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_kpss3[<span class="dv">1</span>])</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical values:'</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value <span class="kw">in</span> result_kpss3[<span class="dv">3</span>].items():</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'</span><span class="ch">\t</span><span class="sc">%s</span><span class="st">: </span><span class="sc">%.4f</span><span class="st">'</span> <span class="op">%</span> (key, value))</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> result_kpss3[<span class="dv">0</span>] <span class="op">&lt;</span> result_kpss3[<span class="dv">3</span>][<span class="st">"5%"</span>]:</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Reject the Ho - The time series is not stationary"</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Do not reject the Ho - The time series is stationary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>KPSS Statistic: 0.384265
p-value: 0.083937
Critical values:
    10%: 0.3470
    5%: 0.4630
    2.5%: 0.5740
    1%: 0.7390
Reject the Ho - The time series is not stationary</code></pre>
</div>
</div>
</section>
<section id="results-analysis-6" class="level5">
<h5 class="anchored" data-anchor-id="results-analysis-6">Results analysis:</h5>
<p>The results of the Kwiatkowski-Phillips-Schmidt-Shin (KPSS) test with constant for the LCE series indicate that we can reject the null hypothesis (Ho) that the time series is not stationary. This is because the value of the KPSS statistic is greater than the critical values at all significance levels, and the p-value is greater than the 5% significance level.</p>
<p>This suggests that the LCE series is stationary in the sense that its mean and variance are constant over time, and that it does not have a deterministic trend. This is important in time series modeling and analysis, as a stationary series may be easier to model and predict.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Kwiatkowski–Phillips–Schmidt–Shin test with constant and trend for the lCE series</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>result_kpss4 <span class="op">=</span> kpss(Y, regression<span class="op">=</span><span class="st">'ct'</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'KPSS Statistic: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_kpss4[<span class="dv">0</span>])</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'p-value: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_kpss4[<span class="dv">1</span>])</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical values:'</span>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value <span class="kw">in</span> result_kpss4[<span class="dv">3</span>].items():</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'</span><span class="ch">\t</span><span class="sc">%s</span><span class="st">: </span><span class="sc">%.4f</span><span class="st">'</span> <span class="op">%</span> (key, value))</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> result_kpss4[<span class="dv">0</span>] <span class="op">&lt;</span> result_kpss4[<span class="dv">3</span>][<span class="st">"5%"</span>]:</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Reject the Ho - The time series is not stationary"</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Do not reject the Ho - The time series is stationary"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>KPSS Statistic: 0.227229
p-value: 0.010000
Critical values:
    10%: 0.1190
    5%: 0.1460
    2.5%: 0.1760
    1%: 0.2160
Do not reject the Ho - The time series is stationary</code></pre>
</div>
</div>
</section>
<section id="results-analysis-7" class="level5">
<h5 class="anchored" data-anchor-id="results-analysis-7">Results analysis:</h5>
<p>The results of the Kwiatkowski-Phillips-Schmidt-Shin (KPSS) test with constant and trend for the ICE series indicate that we cannot reject the null hypothesis (Ho) that the time series is not stationary. This is because the value of the KPSS statistic is less than the critical values at all significance levels, and the p-value is less than the 5% significance level. This suggests that the ICE series is not stationary in the sense that it has a deterministic trend. It is possible that the series is stationary in the sense that its mean and variance are constant over time, but this cannot be determined with the KPSS test with constant and trend.</p>
<p>The results of the unit root tests for both series, there it can be seen that the estimated statistics are less than the critical values at 5% significance. Therefore, it is concluded that the series are integrated of order one in levels and of order zero (stationary) in differences. Additionally, deterministic components such as intercept and trend are included in the tests.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graph both series separately</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">5</span>), nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].plot(data[<span class="st">'LPBI'</span>])</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].plot(data[<span class="st">'LCE'</span>])</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">"LBI series chart"</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">"LCE series chart"</span>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>plt.setp(ax[<span class="dv">0</span>].xaxis.get_majorticklabels(), rotation<span class="op">=</span><span class="dv">90</span>)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>plt.setp(ax[<span class="dv">1</span>].xaxis.get_majorticklabels(), rotation<span class="op">=</span><span class="dv">90</span>)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="VECM_files/figure-html/cell-22-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>In this case, to carry out the Zivot Andrews test, the trend of our series was taken into account; since it captures individually and precisely the structural break of the series. However, using other tests, multiple structural breaks could be obtained, which would make the cointegration task more complex. That is why we only take the trend in our series to identify the breaks produced in the historical evolution of the series.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import libraries</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.stattools <span class="im">import</span> zivot_andrews</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Zivot andrews test with trend for the lPBI series</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>result_za1 <span class="op">=</span> zivot_andrews(data[<span class="st">'LPBI'</span>], trim <span class="op">=</span> <span class="fl">0.15</span>, maxlag<span class="op">=</span><span class="dv">5</span>, regression<span class="op">=</span><span class="st">'t'</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Statistician Zivot Andrews: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_za1[<span class="dv">0</span>])</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'P-value: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_za1[<span class="dv">1</span>])</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical values:'</span>) </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value <span class="kw">in</span> result_za1[<span class="dv">2</span>].items():</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'</span><span class="ch">\t</span><span class="sc">%s</span><span class="st">: </span><span class="sc">%.3f</span><span class="st">'</span> <span class="op">%</span> (key, value))</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Baselag: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_za1[<span class="dv">3</span>])</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>year <span class="op">=</span> data.iloc[result_za1[<span class="dv">4</span>]].name</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Year corresponding to the Breakpoint index: </span><span class="sc">{</span>year<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> result_za1[<span class="dv">0</span>] <span class="op">&lt;</span> result_za1[<span class="dv">2</span>][<span class="st">"5%"</span>]:</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Reject the Ho - The series is stationary in trend"</span>)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Do not reject Ho - The series has a unit root with only one structural break"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Statistician Zivot Andrews: -4.282785
P-value: 0.070014
Critical values:
    1%: -5.034
    5%: -4.406
    10%: -4.137
Baselag: 1.000000
Year corresponding to the Breakpoint index: 1997
Do not reject Ho - The series has a unit root with only one structural break</code></pre>
</div>
</div>
</section>
<section id="results-analysis-8" class="level5">
<h5 class="anchored" data-anchor-id="results-analysis-8">Results analysis</h5>
<p>The null hypothesis of this test is that there is a unit root in the time series with a structural break at some point. In this case, the test returned a statistical value of -4.282785 and a p-value of 0.070014.</p>
<p>Critical values are used to compare with the statistical value and determine whether or not to reject the null hypothesis. In this case, the statistical value is less than the corresponding critical value at the 5% level of significance but not at 1%, indicating that there is insufficient evidence to reject the null hypothesis at the 5% level of significance. However, if a 1% significance level is considered, the statistical value is greater than the corresponding critical value, indicating that there is sufficient evidence to reject the null hypothesis at the 1% significance level.</p>
<p>Therefore, it is concluded that the time series has a unit root with a single structural break in the year 1997 (index 26). It is important to note that the series does not have a stationary trend and that future values of the series may depend on past values. This should be considered when performing analyzes and projections based on the time series in question.</p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Zivot andrews test with trend for the LCE series</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>result_za2 <span class="op">=</span> zivot_andrews(data[<span class="st">'LCE'</span>], trim <span class="op">=</span> <span class="fl">0.15</span> , maxlag<span class="op">=</span><span class="dv">5</span>, regression<span class="op">=</span><span class="st">'t'</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Zivot-Andrews statistic: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_za2[<span class="dv">0</span>])</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'P-value: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_za2[<span class="dv">1</span>])</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical values:'</span>) </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value <span class="kw">in</span> result_za2[<span class="dv">2</span>].items():</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'</span><span class="ch">\t</span><span class="sc">%s</span><span class="st">: </span><span class="sc">%.3f</span><span class="st">'</span> <span class="op">%</span> (key, value))</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Baselag: </span><span class="sc">%f</span><span class="st">'</span> <span class="op">%</span> result_za2[<span class="dv">3</span>])</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>year <span class="op">=</span> data.iloc[result_za2[<span class="dv">4</span>]].name</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Year corresponding to the Breakpoint index: </span><span class="sc">{</span>year<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> result_za2[<span class="dv">0</span>] <span class="op">&lt;</span> result_za2[<span class="dv">2</span>][<span class="st">"5%"</span>]:</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Reject the Ho - The series is stationary in trend"</span>)</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span> (<span class="st">"Do not reject Ho - The series has a unit root with only one structural break"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Zivot-Andrews statistic: -3.112052
P-value: 0.587514
Critical values:
    1%: -5.034
    5%: -4.406
    10%: -4.137
Baselag: 1.000000
Year corresponding to the Breakpoint index: 1996
Do not reject Ho - The series has a unit root with only one structural break</code></pre>
</div>
</div>
</section>
<section id="results-analysis-9" class="level5">
<h5 class="anchored" data-anchor-id="results-analysis-9">Results analysis:</h5>
<p>The null hypothesis of this test is that there is a unit root in the time series with a structural break at some point. In this case, the test returned a statistical value of -3.112052 and a p-value of 0.587514.</p>
<p>Critical values are used to compare with the statistical value and determine whether or not to reject the null hypothesis. In this case, the statistical value is not less than the critical values corresponding to the significance level of 1%, 5%, and 10%, indicating that there is insufficient evidence to reject the null hypothesis. Therefore, the time series is considered to have a unit root with a single structural break in the year 1996 (index 25).</p>
<p>In summary, it cannot be affirmed that the series has a stationary trend, which implies that the future values of the series can depend on the past values. It is important to keep this in mind when performing analyzes and projections based on the time series in question.</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot both series with the structural break</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">5</span>), nrows<span class="op">=</span><span class="dv">1</span>, ncols<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].plot(data[<span class="st">'LPBI'</span>])</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].plot(data[<span class="st">'LCE'</span>])</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">"LBI series chart with structural break"</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">"LCE series chart with structural break "</span>)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].axvline(x<span class="op">=</span><span class="st">'1997'</span>, color<span class="op">=</span><span class="st">'g'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].axvline(x<span class="op">=</span><span class="st">'1996'</span>, color<span class="op">=</span><span class="st">'r'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>plt.setp(ax[<span class="dv">0</span>].xaxis.get_majorticklabels(), rotation<span class="op">=</span><span class="dv">90</span>)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>plt.setp(ax[<span class="dv">1</span>].xaxis.get_majorticklabels(), rotation<span class="op">=</span><span class="dv">90</span>)</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="VECM_files/figure-html/cell-26-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>These results indicate that the null hypothesis of unit root for the series in levels cannot be rejected at any conventional level. The test calculates the breaks that occurred in both series and both are consistent with historical events, such as the privatization process of the electricity sector, which began in 1994 with the sale of distribution companies in Lima, continuing with the sale of generating companies in 1995 and 1996. Likewise, with respect to GDP, the results coincide with the effects of the El Niño phenomenon of 1997-98, which reached great intensity in Peru. In this regard, Contreras et. al (2016), indicate that the El Niño phenomenon constitutes a risk due to a supply shock for the Peruvian economy. When El Niño reaches extraordinary magnitudes, it destroys part of the economy’s capital stock and affects the flow of production of goods and services, all of which generates impacts on potential GDP, amplifying business cycles.</p>
<p>In this sense, to capture the presence of these two structural breaks in our model, we will generate dummy variables for each year in question.</p>
<div class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy variables to identify structural breaks</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'fecha'</span>] <span class="op">=</span> pd.date_range(start<span class="op">=</span><span class="st">'1971-01-01'</span>, end<span class="op">=</span><span class="st">'2014-01-01'</span>, freq<span class="op">=</span><span class="st">'AS'</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'dummy_LPBI'</span>] <span class="op">=</span> np.where(data[<span class="st">'fecha'</span>].dt.year <span class="op">&gt;=</span> <span class="dv">1997</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'dummy_LCE'</span>] <span class="op">=</span> np.where(data[<span class="st">'fecha'</span>].dt.year <span class="op">&gt;=</span> <span class="dv">1996</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>data.head(<span class="dv">30</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="45">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">CE</th>
<th data-quarto-table-cell-role="th">PBI</th>
<th data-quarto-table-cell-role="th">LPBI</th>
<th data-quarto-table-cell-role="th">LCE</th>
<th data-quarto-table-cell-role="th">DLPBI</th>
<th data-quarto-table-cell-role="th">DLCE</th>
<th data-quarto-table-cell-role="th">fecha</th>
<th data-quarto-table-cell-role="th">dummy_LPBI</th>
<th data-quarto-table-cell-role="th">dummy_LCE</th>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">1971</td>
<td>388.514407</td>
<td>8784.738435</td>
<td>9.080771</td>
<td>5.962330</td>
<td>NaN</td>
<td>NaN</td>
<td>1971-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1972</td>
<td>406.578668</td>
<td>8848.246104</td>
<td>9.087975</td>
<td>6.007777</td>
<td>0.720331</td>
<td>4.544718</td>
<td>1972-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1973</td>
<td>410.295619</td>
<td>9158.635033</td>
<td>9.122452</td>
<td>6.016878</td>
<td>3.447789</td>
<td>0.910049</td>
<td>1973-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1974</td>
<td>426.906110</td>
<td>9763.916538</td>
<td>9.186449</td>
<td>6.056564</td>
<td>6.399645</td>
<td>3.968618</td>
<td>1974-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1975</td>
<td>435.773811</td>
<td>9930.384340</td>
<td>9.203354</td>
<td>6.077123</td>
<td>1.690558</td>
<td>2.055922</td>
<td>1975-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1976</td>
<td>444.372471</td>
<td>9828.826562</td>
<td>9.193075</td>
<td>6.096663</td>
<td>-1.027963</td>
<td>1.953978</td>
<td>1976-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1977</td>
<td>472.861818</td>
<td>9621.308071</td>
<td>9.171736</td>
<td>6.158803</td>
<td>-2.133932</td>
<td>6.214010</td>
<td>1977-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1978</td>
<td>466.629163</td>
<td>9134.067535</td>
<td>9.119766</td>
<td>6.145535</td>
<td>-5.196912</td>
<td>-1.326835</td>
<td>1978-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1979</td>
<td>476.986445</td>
<td>9273.244882</td>
<td>9.134889</td>
<td>6.167488</td>
<td>1.512225</td>
<td>2.195321</td>
<td>1979-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1980</td>
<td>499.016545</td>
<td>9581.071923</td>
<td>9.167545</td>
<td>6.212639</td>
<td>3.265612</td>
<td>4.515118</td>
<td>1980-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1981</td>
<td>525.252025</td>
<td>9864.912250</td>
<td>9.196740</td>
<td>6.263878</td>
<td>2.919477</td>
<td>5.123894</td>
<td>1981-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1982</td>
<td>549.297685</td>
<td>9606.151437</td>
<td>9.170159</td>
<td>6.308641</td>
<td>-2.658058</td>
<td>4.476233</td>
<td>1982-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1983</td>
<td>513.679730</td>
<td>8399.468293</td>
<td>9.035924</td>
<td>6.241600</td>
<td>-13.423526</td>
<td>-6.704055</td>
<td>1983-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1984</td>
<td>549.061203</td>
<td>8495.541192</td>
<td>9.047297</td>
<td>6.308210</td>
<td>1.137305</td>
<td>6.660994</td>
<td>1984-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1985</td>
<td>541.510669</td>
<td>8468.238346</td>
<td>9.044078</td>
<td>6.294363</td>
<td>-0.321896</td>
<td>-1.384715</td>
<td>1985-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1986</td>
<td>563.625975</td>
<td>9054.683447</td>
<td>9.111037</td>
<td>6.334391</td>
<td>6.695963</td>
<td>4.002810</td>
<td>1986-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1987</td>
<td>587.769745</td>
<td>9712.858757</td>
<td>9.181206</td>
<td>6.376335</td>
<td>7.016852</td>
<td>4.194442</td>
<td>1987-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1988</td>
<td>550.421426</td>
<td>8599.306113</td>
<td>9.059437</td>
<td>6.310684</td>
<td>-12.176914</td>
<td>-6.565107</td>
<td>1988-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1989</td>
<td>547.161942</td>
<td>7372.997919</td>
<td>8.905580</td>
<td>6.304745</td>
<td>-15.385712</td>
<td>-0.593940</td>
<td>1989-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1990</td>
<td>539.370691</td>
<td>6852.020519</td>
<td>8.832299</td>
<td>6.290403</td>
<td>-7.328082</td>
<td>-1.434174</td>
<td>1990-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1991</td>
<td>571.270273</td>
<td>6857.103080</td>
<td>8.833040</td>
<td>6.347862</td>
<td>0.074149</td>
<td>5.745936</td>
<td>1991-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1992</td>
<td>469.513757</td>
<td>6682.663370</td>
<td>8.807272</td>
<td>6.151698</td>
<td>-2.576844</td>
<td>-19.616483</td>
<td>1992-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1993</td>
<td>515.057446</td>
<td>6893.502315</td>
<td>8.838335</td>
<td>6.244278</td>
<td>3.106266</td>
<td>9.258084</td>
<td>1993-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1994</td>
<td>525.366487</td>
<td>7590.461646</td>
<td>8.934648</td>
<td>6.264096</td>
<td>9.631314</td>
<td>1.981765</td>
<td>1994-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1995</td>
<td>537.198677</td>
<td>7997.691526</td>
<td>8.986908</td>
<td>6.286368</td>
<td>5.226053</td>
<td>2.227191</td>
<td>1995-01-01</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1996</td>
<td>577.702027</td>
<td>8070.283319</td>
<td>8.995944</td>
<td>6.359058</td>
<td>0.903565</td>
<td>7.269021</td>
<td>1996-01-01</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1997</td>
<td>593.880180</td>
<td>8437.797871</td>
<td>9.040477</td>
<td>6.386678</td>
<td>4.453277</td>
<td>2.761937</td>
<td>1997-01-01</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1998</td>
<td>626.766533</td>
<td>8257.345024</td>
<td>9.018858</td>
<td>6.440574</td>
<td>-2.161825</td>
<td>5.389653</td>
<td>1998-01-01</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1999</td>
<td>637.888448</td>
<td>8242.230310</td>
<td>9.017026</td>
<td>6.458163</td>
<td>-0.183213</td>
<td>1.758931</td>
<td>1999-01-01</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2000</td>
<td>661.315738</td>
<td>8336.585137</td>
<td>9.028409</td>
<td>6.494231</td>
<td>1.138270</td>
<td>3.606797</td>
<td>2000-01-01</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import libraries</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.vector_ar.var_model <span class="im">import</span> VAR</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>data1 <span class="op">=</span> data.iloc[:, [<span class="dv">2</span>,<span class="dv">3</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the order of lags</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> VAR(data1)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> [<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>]:</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    result <span class="op">=</span> model.fit(i)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'Lag Order ='</span>, i)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'AIC : '</span>, result.aic)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'BIC : '</span>, result.bic)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'FPE : '</span>, result.fpe)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">'HQIC: '</span>, result.hqic, <span class="st">'</span><span class="ch">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Lag Order = 1
AIC :  -27.668168238678618
BIC :  -27.422419385326027
FPE :  9.639720240944462e-13
HQIC:  -27.577543656488704 

Lag Order = 2
AIC :  -27.922031805644647
BIC :  -27.508300944148605
FPE :  7.492056344826517e-13
HQIC:  -27.77038308159449 

Lag Order = 3
AIC :  -27.783459448694792
BIC :  -27.198337279576247
FPE :  8.644306564017248e-13
HQIC:  -27.570390215296857 

Lag Order = 4
AIC :  -27.906094162559903
BIC :  -27.14609840820863
FPE :  7.71509063479803e-13
HQIC:  -27.63130369569299 

Lag Order = 5
AIC :  -28.03770016604337
BIC :  -27.099280775918952
FPE :  6.871194102520998e-13
HQIC:  -27.701003364249942 
</code></pre>
</div>
</div>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select the order of lags</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> model.select_order(maxlags<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>x.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<table class="simpletable table table-sm table-striped small" data-quarto-postprocess="true">
<caption>VAR Order Selection (* highlights the minimums)</caption>
<tbody>
<tr class="odd">
<td></td>
<td data-quarto-table-cell-role="th">AIC</td>
<td data-quarto-table-cell-role="th">BIC</td>
<td data-quarto-table-cell-role="th">FPE</td>
<td data-quarto-table-cell-role="th">HQIC</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">0</td>
<td>-22.09</td>
<td>-22.00</td>
<td>2.554e-10</td>
<td>-22.06</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1</td>
<td>-27.61</td>
<td>-27.36</td>
<td>1.020e-12</td>
<td>-27.52</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">2</td>
<td>-27.87</td>
<td>-27.44*</td>
<td>7.926e-13</td>
<td>-27.71*</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3</td>
<td>-27.74</td>
<td>-27.14</td>
<td>9.075e-13</td>
<td>-27.52</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">4</td>
<td>-27.85</td>
<td>-27.08</td>
<td>8.156e-13</td>
<td>-27.58</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">5</td>
<td>-28.04*</td>
<td>-27.10</td>
<td>6.871e-13*</td>
<td>-27.70</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>These results refer to the selection of the order of lags for a VAR (Vector Autoregression) model using four information criteria: AIC (Akaike Information Criterion), BIC (Bayesian Information Criterion), FPE (Final Prediction Error) and HQIC (Hannan- Quinn Information Criterion).</p>
<p>Several lag orders have been tested, from 0 to 5. The lowest values of the information criteria (AIC, BIC, FPE, HQIC) indicate that that lag order is the best for the VAR model.</p>
<p>In this case, the selected lag order is 2, since it has the lowest BIC value of all the lag orders tested. In addition, its AIC, FPE, and HQIC value are very close to the minimum value, so it can also be considered as a good option.</p>
</section>
</section>
<section id="cointegration-test" class="level3">
<h3 class="anchored" data-anchor-id="cointegration-test">3.3. Cointegration Test</h3>
<p>As mentioned above, the Johansen test was applied. Below are the results of the Maximum Likelihood Cointegration tests based on the range of the <strong>Π</strong> matrix, the Trace and Maximum Eigenvalue tests. The results of the Cointegration test between real GDP and energy consumption imply that the null hypothesis of no Cointegration in both tests, that is, H<sub>0</sub> is rejected at 5% significance, since the is statistic calculated for each is greater than the critical value.</p>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import libraries</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.vector_ar.vecm <span class="im">import</span> coint_johansen</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 1: Perform Johansen's cointegration test</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>data1 <span class="op">=</span> data.iloc[:, [<span class="dv">2</span>, <span class="dv">3</span>]]</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>array <span class="op">=</span> np.array(data1.values)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>result_cj <span class="op">=</span> coint_johansen(array, det_order<span class="op">=-</span><span class="dv">1</span>, k_ar_diff<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Rank:'</span>, result_cj.ind[<span class="dv">0</span>])</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Eigenvalue:'</span>, result_cj.eig[<span class="dv">0</span>])</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'trace statistic: '</span>, result_cj.trace_stat[<span class="dv">0</span>])</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical value at 5%: '</span>, result_cj.trace_stat_crit_vals[<span class="dv">0</span>][<span class="dv">1</span>])</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Max Eigenvalue: '</span>, result_cj.max_eig_stat[<span class="dv">0</span>])</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Max Critical value at 5%: '</span>, result_cj.max_eig_stat_crit_vals[<span class="dv">0</span>][<span class="dv">1</span>])</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Rank:'</span>, result_cj.ind[<span class="dv">1</span>])</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Eigenvalue:'</span>, result_cj.eig[<span class="dv">1</span>])</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'trace statistic: '</span>, result_cj.trace_stat[<span class="dv">1</span>])</span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Critical value at 5%: '</span>, result_cj.trace_stat_crit_vals[<span class="dv">1</span>][<span class="dv">1</span>])</span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Max Eigenvalue: '</span>, result_cj.max_eig_stat[<span class="dv">1</span>])</span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Max Critical value at 5%: '</span>, result_cj.max_eig_stat_crit_vals[<span class="dv">1</span>][<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rank: 0
Eigenvalue: 0.3461271127934622
trace statistic:  19.63366014549301
Critical value at 5%:  12.3212
Max Eigenvalue:  17.843376956378705
Max Critical value at 5%:  11.2246
Rank: 1
Eigenvalue: 0.04173008304161474
trace statistic:  1.7902831891143038
Critical value at 5%:  4.1296
Max Eigenvalue:  1.7902831891143038
Max Critical value at 5%:  4.1296</code></pre>
</div>
</div>
<p>Based on the result obtained with the Johansen Cointegration Test, the Error Correction Model is derived. In this part, we include in the Error Correction Model, two dummy intervention variables that collect the effects of structural breaks in the variables found with the test of Zivot-Andrews, to take them into account in the short- and long-term adjustment dynamics.</p>
<p>The Granger representation theorem allows us to model short-term and long-term dynamics through an error correction model. However, first the optimal number of lags must be determined, which is obtained through the VAR(p) model. In this case, the optimal number of lags is 2, that is, our VAR model is of order 2, VAR (2). Now, the error correction model (VEC(p-1)) will be a VEC of order 1, that is, VEC(1).</p>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import libraries</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.vector_ar <span class="im">import</span> vecm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Method 2: Perform Johansen's cointegration test</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>vec_rank<span class="op">=</span>vecm.select_coint_rank(data1, det_order<span class="op">=-</span><span class="dv">1</span>, k_ar_diff<span class="op">=</span><span class="dv">1</span>, method<span class="op">=</span><span class="st">'trace'</span>, signif<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(vec_rank.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Johansen cointegration test using trace test statistic with 5% significance level
=====================================
r_0 r_1 test statistic critical value
-------------------------------------
  0   2          19.63          12.32
  1   2          1.790          4.130
-------------------------------------</code></pre>
</div>
</div>
<p>The result of the Johansen cointegration test indicates that for r = 0, the value of the trace test statistic is 19.63. The corresponding critical value for a significance level of 5% is 12.32. Since the value of the test statistic is greater than the critical value, one can reject the null hypothesis that there is no cointegration between the variables and conclude that there is at least one cointegration relationship between them.</p>
<div class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get maximum eigenvalues</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>vec_rank1<span class="op">=</span>vecm.select_coint_rank(data1, det_order<span class="op">=-</span><span class="dv">1</span>, k_ar_diff<span class="op">=</span><span class="dv">2</span>, method<span class="op">=</span><span class="st">'maxeig'</span>, signif<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(vec_rank1.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Johansen cointegration test using maximum eigenvalue test statistic with 5% significance level
=====================================
r_0 r_1 test statistic critical value
-------------------------------------
  0   1          12.77          11.22
  1   2          3.527          4.130
-------------------------------------</code></pre>
</div>
</div>
<div class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>dummies <span class="op">=</span> data.iloc[:, [<span class="dv">7</span>, <span class="dv">8</span>]]</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>array <span class="op">=</span> np.array(dummies.values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Based on the VEC model, after applying the Johansen Cointegration Test between energy consumption and GDP, the adjustment dynamics in the short and long term can be analyzed.</p>
<div class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import Libraries</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.vector_ar.vecm <span class="im">import</span> VECM</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="55">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply the error correction model (VECM)</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>vecm <span class="op">=</span> VECM(data1, exog<span class="op">=</span>dummies, k_ar_diff<span class="op">=</span><span class="dv">1</span>, coint_rank<span class="op">=</span><span class="dv">1</span>, deterministic<span class="op">=</span><span class="st">'n'</span>, dates<span class="op">=</span>data[<span class="st">'fecha'</span>], )</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>vecm_fit <span class="op">=</span> vecm.fit()</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(vecm_fit.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Det. terms outside the coint. relation &amp; lagged endog. parameters for equation LPBI
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
exog1         -0.0428      0.050     -0.852      0.394      -0.141       0.056
exog2          0.0088      0.049      0.179      0.858      -0.088       0.106
L1.LPBI        0.4775      0.163      2.924      0.003       0.157       0.797
L1.LCE        -0.1407      0.170     -0.828      0.408      -0.474       0.192
Det. terms outside the coint. relation &amp; lagged endog. parameters for equation LCE
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
exog1         -0.0159      0.043     -0.369      0.712      -0.100       0.069
exog2         -0.0657      0.042     -1.548      0.122      -0.149       0.017
L1.LPBI        0.2175      0.140      1.555      0.120      -0.057       0.492
L1.LCE        -0.5215      0.146     -3.582      0.000      -0.807      -0.236
                Loading coefficients (alpha) for equation LPBI                
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
ec1            0.0275      0.016      1.678      0.093      -0.005       0.060
                Loading coefficients (alpha) for equation LCE                 
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
ec1            0.0812      0.014      5.791      0.000       0.054       0.109
          Cointegration relations for loading-coefficients-column 1           
==============================================================================
                 coef    std err          z      P&gt;|z|      [0.025      0.975]
------------------------------------------------------------------------------
beta.1         1.0000          0          0      0.000       1.000       1.000
beta.2        -1.2557      0.020    -61.722      0.000      -1.296      -1.216
==============================================================================</code></pre>
</div>
</div>
<p>The results show that in the short term, the L1.LPBI coefficient is positive and significant at the 1% level, which indicates that in the short term, a variation in the GDP growth rate (LPBI) will translate into a increase in its own growth rate in the same period. On the other hand, the L1.LCE coefficient is negative but not statistically significant, which suggests that the growth rate of electricity consumption (LCE) does not significantly affect the GDP growth rate in the short term.</p>
<p>In this order of ideas, the energy conservation hypothesis is fulfilled for the Peruvian economy in the short term. Regarding the long-term relationships, the results of the cointegration relationships can be analyzed in the last table. Where we can see that the beta.2 coefficient is negative and significant at the 1% level, which indicates that in the long term there is a direct relationship between the growth rate of Peru’s GDP and the growth rate of energy consumption in Peru . In other words, in the long term, an increase in energy consumption of 1% generates an increase in GDP of 1,256%, therefore, in the long term, energy consumption does affect GDP.</p>
<p>Finally, the adjustment coefficient (speed of adjustment) to long-term imbalances of the model (∆LPIB) is 2.75%, while which for the model (∆LCE) is 8.12%. This implies a faster adjustment in the energy consumption error correction model.</p>
<div class="cell" data-execution_count="56">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make forecasts</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>vecm1 <span class="op">=</span> VECM(data1, k_ar_diff<span class="op">=</span><span class="dv">2</span>, coint_rank<span class="op">=</span><span class="dv">1</span>, deterministic<span class="op">=</span><span class="st">'n'</span>, dates<span class="op">=</span>data[<span class="st">'fecha'</span>])</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>vecm_fit1 <span class="op">=</span> vecm1.fit()</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>vecm_fit1.plot_forecast(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="VECM_files/figure-html/cell-40-output-1.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="conclusiones" class="level2">
<h2 class="anchored" data-anchor-id="conclusiones">4. Conclusiones</h2>
<p>In this article, the short- and long-term relationship between energy consumption and real GDP for the Colombian economy during the period 1970-2009 was analyzed, using annual time series. First, the long-term elasticity of energy consumption to real GDP was estimated and then, under the VEC modeling, the short- and long-term dynamics were recognized.</p>
<p>The empirical results for the Peruvian case suggest the existence of a long-term bidirectional causal relationship between energy consumption and GDP. In other words, the fact that there is cointegration between the variables confirms the relationship between them, that is, it suggests that in the long term there is a feedback between energy consumption and GDP.</p>
<p>In summary, the results indicate that in the short term there is no relationship between energy consumption and GDP, but there is in the long term, so our results can be placed under the long-term energy conservation hypothesis. term and a long-term feedback effect.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Abosedra, A., et al.&nbsp;(1991). New evidence on the causal relationship between U.S. Energy consumption y Gross National product. Journal of Energy and Development.</li>
<li>Al-iriani, M. (2006). Energy GDP relationship revisted: an example from GCC countries using panel causality. Energy Policy.</li>
<li>Dickey, D. &amp; Fuller, W. (1979). Distribution of the Estimators for Autoregressive Time Series with a Unit Root. Journal of the American Statistical Association.</li>
<li>Erol, et al.&nbsp;(2001). On the causal relationship between energy and income for industrialized countries. Journal of Energy Development.</li>
<li>Granger, C. &amp; Newbold, P. (1974). Spurious Regressions in Econometrics. Journal of Econometrics, vol.&nbsp;2: 111-120, 1974.</li>
<li>Hwang, D. &amp; Gum, B. (1992). The causal relationship between energy and GNP: the case of Taiwan. Journal of Energy and Development.</li>
<li>Johansen, S. (1988). Statistical analysis of cointegration vectors. Journal of Economic Dynamics and Control, vol.&nbsp;12.</li>
<li>Ozturk et at. (2010). The causal relationship between energy consumption and GDP in Albania, Bulgaria, Hungary and Romania: Evidence from ARDL bound testing approach. Applied Energy, Elsevier, vol.&nbsp;87.</li>
<li>Sims, C. (1980). Macroeconomics and Reality. Econométrica, vol.&nbsp;48(1): 1-48.</li>
<li>Soytas et al.&nbsp;(2001). Energy Consumption and GDP Relations in Turkey: A Cointegration and Vector Error Correction Analysis. Economics and Business in Transition: Facilitating Competitiveness and Change in the Global Environment Proceedings. Global Business and Technology Association.</li>
<li>Yu et al.&nbsp;(1984). The relationship between energy and GNP: further results. Energy Economics, vol.&nbsp;6: 186-190, 1984.</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>